name = "breakaway"
compatibility_date = "2026-01-01"
assets = { directory = "./public", not_found_handling = "single-page-application" }

[[custom_domains]]
hostname = "breakaway.napawan.com"
zone_id = "9be7d8dd6d684c40a7b43319a476640a"
